### ISSUE TITLE
How to download the tilesets?

### ISSUE THREAD

**Issue by Westerrr** [PMDCollab/RawAsset#1]
Hello, I have seen the pmd tilesets at 
https://github.com/PMDCollab/RawAsset/tree/master/TileDtef

However, I don't know how to download them without downloading every single folder and file. Is there a way to download only the tilesets??

Thank you very much in advance and kind regards

**Comment by audinowho** [comment]
You can download the whole thing in a zip from the main page: https://github.com/PMDCollab/RawAsset 
Click on Code, and then choose Download Zip
![image](https://user-images.githubusercontent.com/2676737/229629409-2c9888d7-3823-4fa0-8448-52368345188c.png)

This is the only way to get all tilesets.
